spring:
  application:
    name: spring-security-application
  datasource:
    url: jdbc:postgresql://localhost:5432/springsecurity
   # url: jdbc:mysql://localhost:3306/security
    username: keycloak
    password: keycloak
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080

logging:
  level:
    root: info

